### ISSUE TITLE
Uploading file to non-existing partitioned dataset with specified DCB parms fails

### ISSUE THREAD

**Issue by radecek9787** [zowe/zowe-cli-ftp-plugin#106]
I want to upload a local file to a partitioned dataset that does not exist. So I use the **zowe zftp ul ftds** command with **--dcb option** to specify DCB parameters for the new partitioned dataset. **But this command fails:**

`zowe zftp ul ftds sample.bin "TEST.DS01(SAMPLE)" -b --dcb "DSORG=PO RECFM=VB LRECL=27994 BLKSIZE=32760 PRIMARY=100 SECONDARY=200"`

```
Command Error:
TEST.DS01(SAMPLE) requests a nonexistent partitioned data set.  Use MKD command to create it.
```

When I do the same for a sequential dataset, it works:
`zowe zftp ul ftds sample.bin "TEST.DS01" -b --dcb "DSORG=PO RECFM=VB LRECL=27994 BLKSIZE=32760 PRIMARY=100 SECONDARY=200"`
       
`Uploaded from local file 'sample.bin' to TEST.DS01`

**Comment by tiantn** [comment]
Hi @radecek9787 , thank you for openning the issue. We consider upload local file to a nonexistent partitioned dataset as two atomic operations: first allocate the dataset and then upload it to a member.

Actually you can gennerally think the PS dataset and member are files and PO dataset is a direcotory. So we need have the directory first then upload files. Thank you!

**Comment by radecek9787** [comment]
Hi @tiantn , I understand, but if it works as designed, then help for --dcb should be improved. It does not say it can be used just for PS dataset. It says DCB parameters for dataset allocation if not existing, which is true also for PO dataset in my example. Thank you :-)

```
 --dcb  (string)

      DCB parameters for dataset allocation if not existing. It's space separated like
      RECFM=FB LRECL=326 BLKSIZE=23472
```

**Comment by tiantn** [comment]
Hi @radecek9787 , you are right. We should clearly state the scope of  using the --dcb. Thank you. I will improve the description. 😊

**Comment by radecek9787** [comment]
Great, thank you @tiantn !
