### ISSUE TITLE
SPACETYPE=CYLINDER not accepted for zowe zftp alloc ds

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli-ftp-plugin#115]
For most command options in the `--dcb` parm it seems like an `=` is accepted; however, it is not for `SPACETYPE`.  e.g.:

`zowe zftp allocate ds IBMUSER.REXX --dcb "KELDA16.RECFM=FB LRECL=80 RECFM=FB BLKSIZE=80 DSORG=PO SPACETYPE CYLINDER 
PRIMARY=10 SECONDARY=5 DIRECTORY=20 PDSTYPE=PDSE`

will successfully allocate my data set using cylinders while:

`zowe zftp allocate ds IBMUSER.REXX --dcb "KELDA16.RECFM=FB LRECL=80 RECFM=FB BLKSIZE=80 DSORG=PO SPACETYPE=CYLINDER 
PRIMARY=10 SECONDARY=5 DIRECTORY=20 PDSTYPE=PDSE` 

does not.

**Comment by dkelosky** [comment]
Somewhat related, `SECONDARY 5`  doesn't appear to be accepted with or without `=`.

**Comment by std4lqi** [comment]
The `dcb` parameters are passed to FTP with `site` command. Actually, no sub-command `SPACETYPE` and `DSORG` in `site`, but `CYlinders` exits. Either `CY` or `CYLINDER` works. So the following should be good.

```
--dcb "LRECL=80 RECFM=FB BLKSIZE=80 CYLINDER PRIMARY=5 SECONDARY=10 DIRECTORY=20 PDSTYPE=PDSE"
```

In terms of ` PRIMARY` or `SECONDARY`, I observed sometimes dataset is not allocated with the exact PRIMARY/SECONDARY value. In my case, only 9 cylinders are allocated from FTP, either `PRIMARY=10` or `SECONDARY=10`. When I change to 5 cylinders, both are good. Maybe some other things determine the actual space allocated.

The details can be found at https://www.ibm.com/docs/en/zos/2.3.0?topic=subcommands-site-subcommandsend-site-specific-information-host. We may list some relevant to allocation in zftp `alloc ds` help.

**Comment by dkelosky** [comment]
ok thank you for the clarification.  I took `SPACETYPE` from [here](https://github.com/IBM/zos-node-accessor/tree/1.0.7#mvs-dataset-or-uss-files)

Thanks for getting back so quickly; this plug in works great

**Comment by std4lqi** [comment]
Hi @dkelosky , I refined the description of dataset allocation at https://github.com/IBM/zos-node-accessor/pull/76. Let me know please, if any comments. Thanks!
