### ISSUE TITLE
zowe zftp view ds partitioned data set error

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli-ftp-plugin#116]
If I try to view a partitioned data set that exists but doesn't have any members, I get an error
```
zowe zftp view ds IBMUSER.REXX            
Command Error:
Client network socket disconnected before secure TLS connection was established
```

If the data set is physical sequential (`RECFM=PS`) I get proper message indicating whether a data set exists or not.  How do I test whether a `PO` type data set exists via `zftp` plugin?   

Thanks

**Comment by dkelosky** [comment]
It looks like I get two different errors for the same condition.  Running the command successively yields different results, here is the output for two command runs with `--rfj` option:
```
C:\dev\node>zowe zftp view ds IBMUSER.REXX --rfj
{
  "success": false,
  "exitCode": 1,
  "message": "Retrieval of a whole partitioned data set is not supported. Use MGET or MVSGET for this purpose.",
  "stdout": "",
  "stderr": "\u001b[31mCommand Error:\u001b[39m\n\u001b[31m\u001b[39mRetrieval of a whole partitioned data set is not supported. 
Use MGET or MVSGET for this purpose.\n",
  "data": {},
  "error": {
    "msg": "Retrieval of a whole partitioned data set is not supported. Use MGET or MVSGET for this purpose.",
    "causeErrors": [
      {
        "code": 550
      }
    ]
  }
}
C:\dev\node>zowe zftp view ds IBMUSER.REXX --rfj
{
  "success": false,
  "exitCode": 1,
  "message": "Client network socket disconnected before secure TLS connection was established",
  "stdout": "",
  "stderr": "\u001b[31mCommand Error:\u001b[39m\n\u001b[31m\u001b[39mClient network socket disconnected before secure TLS connection was established\n",
  "data": {},
  "error": {
    "msg": "Client network socket disconnected before secure TLS connection was established",
    "causeErrors": [
      {
        "code": "ECONNRESET",
        "host": "xxx.net"
      }
    ]
  }
}
```

**Comment by std3lqi** [comment]
The message `Client network socket disconnected before secure TLS connection was established` shows up when FTP connection is off for some reason, like z/OS is busy, or FTP runs with very low priority. It might happen with any FTP operation. You can try it again, for a couple of times or later, to see whether it persists. Thanks!

**Comment by dkelosky** [comment]
Understood, thanks for follow up
