### ISSUE TITLE
Upload File-To-Data-Set example shows invalid command

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli-ftp-plugin#129]
The second example in the documentation at [https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-ftp_upload_file-to-data-set](https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-ftp_upload_file-to-data-set) and the example provided in zowe-cli-ftp-plugin/src/cli/upload/file-to-data-set/FileToDataSet.definition.ts appear to show a user allocating and uploading a file to a PDS member, which is not possible even with the PDSTYPE=PDS parameter provided for the --dcb option. 

Current state of the example in question: 

`zowe zos-ftp upload file-to-data-set iefbr14.txt "ibmuser.cntl(iefbr14)" --dcb "RECFM=FB LRECL=326 BLKSIZE=23472"`

To avoid confusion, I propose that this example be revised to something like:

`zowe zos-ftp upload file-to-data-set dataset.txt "ibmuser.dataset" --dcb "RECFM=FB LRECL=326 BLKSIZE=23472"`

**Comment by tiantn** [comment]
Thank you @adam-wolfe ! You are right. Thank you for this finding! We will fix it according your suggestions. Thank you very much!
