### ISSUE TITLE
streamToStream does not handle optional parameters correctly

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-cli-ftp-plugin#26]
In `src/api/StreamUtils.ts` the method `streamToStream()` define the optional parameter `result`.

However, that optionality is only checked once. In other places (lines 90 and 94) it causes the method to crash and the promise is never resolved.

**Comment by phaumer** [comment]
I recommend adding `"strictNullChecks": true` to `tsconfig.json` to catch error like these.

**Comment by std4lqi** [comment]
Thanks, @phaumer! 

As you mentioned in #27, some test for `CreateDataSet` would be needed with `"strictNullChecks": true`. I'll follow up #27 later, fixing this issue by checking this optional response first in PR #28.

**Comment by std4lqi** [comment]
Oh, just realized #27 is PR. The #28 can be ignored then. Thanks, @phaumer !
