### ISSUE TITLE
Provide an exported API

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-cli-ftp-plugin#29]
The API folder does currently does not export. 
- Should move more API business logic of interacting with the zos-accessor into the API
- Need to export API with index files so third party extension such as Zowe Explorer can use it.

**Comment by phaumer** [comment]
I would be happy to help with this.

**Comment by std4lqi** [comment]
Hi @phaumer , 

Does it mean the individual command handler will not use `params.connection` directly, but the APIs exposed in api folder, like `CreateDataset`?

**Comment by phaumer** [comment]
@std4lqi yes, that is what I am thinking as I want to call FTP in the Zowe Explorer and currently have to copy paste the code from the command handlers to make it happen. I would like to move all non-command handler specific code into the api package for others to reuse similar to how the core CLI and other plugins are implemented. Do you agree with that?

**Comment by std4lqi** [comment]
Hi @phaumer, it's good idea to extend this plugin's capability to Zowe Explorer. I definitely agree with it.

As I understand, Zowe Explorer is ZLUX app. So this zos-ftp plugin will be possibly used in ZLUX? Any big view you could share would be appreciated.

**Comment by phaumer** [comment]
@std4lqi I am referring to the VS Code extension. I am working on this Issue https://github.com/zowe/vscode-extension-for-zowe/issues/279 that will add abstractions so that you do not have to rely on zOSMF, but can use any other protocol such as FTP, SSH, ZSS etc. I am creating a PR soon that will use your plugin to implement the USS tree browser interactions using FTP as a first prototype.

**Comment by std4lqi** [comment]
@phaumer I see now. Thanks for your information.

**Comment by phaumer** [comment]
@std4lqi I pushed a branch now. You see the FTP code here, which borrows heavily from your handler: https://github.com/zowe/vscode-extension-for-zowe/blob/extension-api/src/api/ZoweVscFtpRestApi.ts

**Comment by std4lqi** [comment]
@phaumer  I suppose we can close this issue now? A thin layer of APIs are exposed via DataSetUtils, JobUtils, and UssUtils now.

**Comment by std4lqi** [comment]
Close this issue, as a thin layer of APIs are exposed via DataSetUtils, JobUtils, and UssUtils now.
