### ISSUE TITLE
Publish plugin to npmjs

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-cli-ftp-plugin#31]
The README  mentions that the plugin can be installed via `zowe plugins install @zowe/zos-ftp-for-zowe-cli@latest`, but I do not see it being published on npmjs.org, yet.

**Comment by std4lqi** [comment]
I'm afraid it should be `zowe plugins install @zowe/zos-ftp@latest`. I'm very likely confusing the plugin name and node.js module name. :-(

@zFernand0, is any staging npm registry with this plugin published? I'd like to walk through the steps in README and doc as well. Thanks!

**Comment by zFernand0** [comment]
Plugin has been published. 
https://www.npmjs.com/package/@zowe/zos-ftp-for-zowe-cli
😄
