### ISSUE TITLE
Make USS directory

### ISSUE THREAD

**Issue by tiantn** [zowe/zowe-cli-ftp-plugin#47]
It is a common operation in USS environment.

**Comment by zFernand0** [comment]
Is it possible to allow for a `zowe zftp submit [uss-command|uss]`? 
That way the user is not blocked waiting on new commands when it comes to USS functionality. 😋

**Comment by std4lqi** [comment]
FTP protocol doesn't provide the command to execute uss command. But the MKdir command of FTP can create PDS, PDSE, or z/OS Unix Directory on z/OS.
