### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by chipset** [zowe/zowe-cli-ftp-plugin#49]
ZOSMF and ZFTP plugins are offering similar capabilities but with different output.  The calls are very similar, for example: zowe **jobs** view jsbj JOBXXXXX and zowe **zftp** view jsbj JOBXXXXX.

However the output is different for return codes.
ZOSMF: 
jobid:   JOB08946
retcode: CC 0004
jobname: MBBLMN01
status:  OUTPUT

ZFTP:
jobname: MBBLMN01
jobid:   JOB08946
owner:   CUST001
status:  OUTPUT
rc:      4

Any named options are the same, with the exception of rc/retcode.  Not only are the names different, but the output differs slightly.  Can these be normalized to one output?  It would make it easier for customers moving between the plugins or migrating from ZFTP to ZOSMF over time.

**Comment by std4lqi** [comment]
@chipset Many thanks for the feedback! I agree to have `retcode` in ZFTP output to make user easy to move from one to another.
