### ISSUE TITLE
Support SDK initiative - SubmitJobHandler

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-ftp-plugin#57]
Having a Common/Base handler is nice. However, shouldn't most of this logic be contained in the Plugin "SDK" (or the TS APIs of the plugin, i.e. `api` folder and exported as such)?
That way it's easier for the https://github.com/zowe/zowe-explorer-ftp-extension/ to consume instead of having to workaround handlers 😋

_Originally posted by @zFernand0 in https://github.com/zowe/zowe-cli-ftp-plugin/pull/55#discussion_r450250722_

**Comment by std4lqi** [comment]
@zFernand0 I suppose we can close this issue now? A thin layer of APIs are exposed via `DataSetUtils`, `JobUtils`, and `UssUtils` now.

**Comment by zFernand0** [comment]
Thanks @std4lqi! 😋
