### ISSUE TITLE
Support downloading variable length dataset

### ISSUE THREAD

**Issue by std4lqi** [zowe/zowe-cli-ftp-plugin#58]
For VB or VBS dataset, the record length is variable. Usually, it can be downloaded via FTP with FTP command `site rdw`, which inserts 4-byte RDW (Record Description Word) at the beginning of each variable-length record, so that the tool is able to recognize the individual records correctly.

We may add an option `--rdw` in ZFTP `download dataset` sub command, indicating ZFTP to submit `site rdw` before `get` command.

I don't know whether the plugin invoking z/OSMF for dataset downloading has the similar option. If so, we may refer to its option name. Thanks!

**Comment by dkelosky** [comment]
Thanks @std4lqi for checking.  I don't think there is anything similar in the Zowe CLI command groups to the `site rdw` requirement that you have though.

This seems like a cool update 😄

**Comment by std4lqi** [comment]
The option `--rdw` was added in 1.5.0.
