### ISSUE TITLE
Allow passing a pattern to zowe zftp ls uss-files

### ISSUE THREAD

**Issue by peterpk** [zowe/zowe-cli-ftp-plugin#63]
According to documentation, the `zowe zftp ls uss-files` command accepts only a _directory_ name as argument, and lists all files in the directory.  If given a file name, or a file pattern, it returns an error:

> Unrecognized file list header: _(followed by the first line of directory output)_

It would be nice if the `ls uss-files` command accepted a pattern and returned only those directory files which match the pattern.  Full globbing would be **awesome** but I'll settle for the prefix-matching (i.e. patterns that end with `*`) functionality that is provided by the standard z/OS FTP command line client.

Thanks!

**Comment by std4lqi** [comment]
Thanks, @peterpk! We'll look into it soon.

**Comment by std4lqi** [comment]
@peterpk Sorry for coming back on it so late.

We're working on supporting some common ones like the following containing `*` as follows:

- /u/user/prefix*
- /u/user/*.txt
- /u/user/prefix*.txt

I suppose it's easy to add `| grep pattern` to do more complicated file name filtering. 

Thanks for your feedback again!

**Comment by tiantn** [comment]
Hi @peterpk , now the version 1.8.0 of zftp supported to list uss with pattern. Could you help to try and verify it? Thank you very much!

**Comment by peterpk** [comment]
I confirmed that it works with examples like `zowe zftp ls uss-files /u/kidwell/*.txt` and `zowe zftp ls uss-files /u/kidwell/bin/cu*` .  Even `zowe zftp ls uss-files /u/kidwell/bin/cu*l` worked -- nice job!

**Comment by tiantn** [comment]
Thanks @peterpk for helping verify the fix.
