### ISSUE TITLE
zOS FTP Multiple UNIX processes

### ISSUE THREAD

**Issue by mmoore96** [zowe/zowe-cli-ftp-plugin#78]
I began using this FTP extension in April 2021. I am currently a zOS developer and last week one of system programmers noticed that I had around 55 FTP streams (UNIX processes) open.
We did some digging around and found that it was secondary to using this extension. 
It appears that every time I refresh a dataset or submit a job or do anything kind of request on VS code, it opens a new FTP session.
The only way for them to be closed is by exiting VS Code. 

I am unable to use this extension now due to this reason. 

It seems like the extension should only allow one FTP stream (UNIX process) open to send requests to and from zOS. Or just close it after some time like 1 minute if it is going to continue to open new FTP sessions. 

I believe that @tiantn implemented the FTP process in: 
https://github.com/zowe/vscode-extension-for-zowe/pull/1219
https://github.com/zowe/vscode-extension-for-zowe/pull/1252

Thank you all for working on this tool! I love it and would like to continue to use it!

All the best, 
George Moore

**Comment by std4lqi** [comment]
@mmoore96 Thanks for the feedback! 

We received a similar one at https://github.com/zowe/vscode-extension-for-zowe/issues/1196, and will work out a shared connections solution.

**Comment by mmoore96** [comment]
@std4lqi  Thank you for pointing out the already open issue. I did not see that one.
Do you all have a date of when this fix will be moved to production?

Thank you!

**Comment by std4lqi** [comment]
@mmoore96 We started to work on it, but don't have a date yet. Appreciate it, if you are willing to verify the build with fix. Thanks!

**Comment by mmoore96** [comment]
@std4lqi Great! I would be happy to!

**Comment by mmoore96** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/1324

**Comment by mmoore96** [comment]
@std4lqi I saw in the above pull request that others performed testing. I know version 1.16.0 is not out yet. But I did build the vsix file and tested it. I can confirm that the only 1 FTP stream is being used and disappears once the request is complete. 
Everything is working great! I want to thank @tiantn for the strong work! I am happy to be able to utilize this extension again!

**Comment by std4lqi** [comment]
@mmoore96  Oh, you tried it already. Thanks for your feedback! Zowe Explorer Extension for FTP 1.16.0 is released now.
