### ISSUE TITLE
"PASS command failed" Meaning is Unclear

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli-ftp-plugin#85]
If I run a `zowe zftp list jobs` command with an invalid password I get:
```
C:\dev\node\zowe-cli-ftp-plugin>zowe zftp list jobs
Command Error:
PASS command failed
```

I didn't realize that `PASS command failed` was talking about a password error.  Should the error and information be more generically presented for credential errors?

**Comment by tiantn** [comment]
Hi @dkelosky , this issue was fixed in zftp 1.7.0. Could you help to verify it? Thank you!
