### ISSUE TITLE
Can't delete USS directory with segment longer than 8 characters

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli-ftp-plugin#92]
The system test ["should be able to mkdir a directory tree on uss then delete them recursively"](https://github.com/zowe/zowe-cli-ftp-plugin/blob/master/__tests__/__system__/cli/delete/uss-file/cli.delete.uss-file.test.ts#L75-L111) fails for me.

I can reproduce the error when trying to delete the directory tree that the test created using Zowe CLI:
```
zowe zftp delete uss-file /tmp/user001/K316ZM953Y -f --recursive
Command Error:
Invalid data set name "'\tmp\user001\K316ZM953Y\RG5C0K47FL.txt'".  Use MVS Dsname conventions.
```

From a quick look at the UssUtils API it seems that its calling `connection.deleteDataset`. I'm not familiar with the "zos-node-accessor" package, but perhaps updating to version 2.x which has a `connection.deleteFile` method would fix this?

**Comment by t1m0thyj** [comment]
Should I create a pull request for this? 🙂

**Comment by tiantn** [comment]
> Should I create a pull request for this? 🙂

Hi @t1m0thyj , we are preparing the PR but it is great if you are ready for this PR. Thank you! 😊

**Comment by tiantn** [comment]
Hi @t1m0thyj , I changed PATH.join to PATH.posix.join and verified it worked in windows. But when I run the system test in windows it seems can't execute a CLI script (runCliScript function in TestUtils.ts). Do you change the code to run the system tests in windows? Thank you!

**Comment by t1m0thyj** [comment]
@tiantn Sorry for the delayed response, I pulled down the branch for your PR #94 and all the system tests pass for me on Windows. I have not made any changes besides configuring test properties in the custom_properties.yaml file.
